project:
  type: website
  # 正しいルート(05_stockTrading)へ戻るためには3階層遡れば良い: quarto -> by_timeSeries -> 03_analysis_base
  output-dir: ../../../docs/quarto/latest

website:
  title: "ちょこっと"
  site-url: https://chiquitos-jp.github.io/trading-dashboard/
  navbar:
    background: "#f8fafc" # ナビバー背景色
    foreground: "#4b5563" # ナビバー文字色
    logo: assets/chokotto_ver01.png
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      - href: dashboard.qmd
        text: Dashboard
    right: []
    tools:
      - icon: github
        href: https://github.com/Chiquitos-JP/trading-dashboard
        aria-label: GitHub repository
  page-footer:
    center: "© 2025 chokkoto All rights reserved."
    right:
      - icon: github
        href: https://github.com/Chiquitos-JP/trading-dashboard

format:
  html:
    theme:
      light: default
    css: styles.scss
    toc: true
